services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code
      - ./src:/ros2_ws/src
      # Persistent volumes for build artifacts
      - ros2_build:/ros2_ws/build
      - ros2_install:/ros2_ws/install
    # Windows doesn't support host network mode, so we expose ports instead
    ports:
      - "11311:11311"  # For ROS master
      - "9090:9090"    # For rosbridge (if used)
    environment:
      # ROS2 environment
      - ROS_DOMAIN_ID=0
    # Use bridge network instead of host for Windows compatibility
    networks:
      - ros2_net
    command: bash
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY

volumes:
  ros2_build:
  ros2_install:

networks:
  ros2_net:
    driver: bridge
